@echo off
setlocal enabledelayedexpansion

echo ============================================================
echo   AR Learning Platform - Auto Tunnel Setup
echo ============================================================

REM Kill existing processes
echo.
echo [*] Cleaning up existing services...
taskkill /F /IM python.exe >nul 2>&1
taskkill /F /IM node.exe >nul 2>&1
taskkill /F /IM cloudflared.exe >nul 2>&1
timeout /t 2 /nobreak >nul

REM Start Backend
echo.
echo [1/4] Starting Backend on port 8000...
start /MIN "Backend" cmd /c "cd backend && uvicorn main:app --reload > ../backend.log 2>&1"
timeout /t 4 /nobreak >nul

REM Start Cloudflare Tunnel
echo [2/4] Creating Cloudflare Tunnel...
start /MIN "Tunnel" cmd /c "cloudflared.exe tunnel --url http://localhost:5173 > tunnel.log 2>&1"
timeout /t 10 /nobreak >nul

REM Extract tunnel URL
echo [3/4] Extracting tunnel URL...
for /f "tokens=*" %%i in ('findstr /r "https://.*\.trycloudflare\.com" tunnel.log') do (
    set TUNNEL_LINE=%%i
    goto :found
)
:found
for /f "tokens=2 delims= " %%j in ("!TUNNEL_LINE!") do set TUNNEL_URL=%%j

if "!TUNNEL_URL!"=="" (
    echo [ERROR] Could not extract tunnel URL!
    type tunnel.log
    pause
    exit /b 1
)

echo.
echo ============================================================
echo   Tunnel URL: !TUNNEL_URL!
echo ============================================================

REM Update .env file
echo [4/4] Updating frontend .env...
(
    echo # Auto-generated by start-dev.bat - %date% %time%
    echo VITE_API_BASE=http://localhost:8000
    echo VITE_WS_URL=ws://localhost:8000
    echo.
    echo # Cloudflare Tunnel URL
    echo VITE_PUBLIC_TUNNEL_URL=!TUNNEL_URL!
) > frontend-web\.env

echo [SUCCESS] .env updated with new tunnel URL

REM Start Frontend
echo.
echo [5/5] Starting Frontend on port 5173...
start "Frontend" cmd /k "cd frontend-web && npm run dev"

timeout /t 3 /nobreak >nul

echo.
echo ============================================================
echo   [SUCCESS] All services started!
echo.
echo   Backend:  http://localhost:8000
echo   Frontend: http://localhost:5173
echo   Public:   !TUNNEL_URL!
echo.
echo   Open this URL on your phone: !TUNNEL_URL!
echo ============================================================
echo.
echo Press any key to STOP all services...
pause >nul

echo.
echo [*] Stopping all services...
taskkill /F /IM python.exe >nul 2>&1
taskkill /F /IM node.exe >nul 2>&1
taskkill /F /IM cloudflared.exe >nul 2>&1
echo [SUCCESS] All services stopped!
timeout /t 2 /nobreak >nul
