import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, StyleSheet, Text, View } from 'react-native';
import { ClayButton } from './ClayButton'; import { ClayCard } from './ClayCard';
import { coursesApi } from '../services/api'; import { BRAND, COLORS, FONT, SPACING } from '../design/tokens';
import type { LessonActivity, MemoryMatchCard } from '../types/course';
type Game = Extract<LessonActivity, { type: 'mini_game' }>;
export const CourseGameActivityRenderer: React.FC<{activity: Game; courseId:string; lessonId:string; onComplete:()=>void}> = ({activity,courseId,lessonId,onComplete}) => {
 const [cards,setCards]=useState<MemoryMatchCard[]>([]),[picked,setPicked]=useState<string[]>([]),[matched,setMatched]=useState<string[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[finishing,setFinishing]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try { const d=(await coursesApi.getMiniGameActivity(courseId,lessonId,activity.activity_id)).data; if(d.game_type!=='memory_match'||!d.cards.length) throw new Error(); setCards([...d.cards].sort((a,b)=>a.card_id.localeCompare(b.card_id))); } catch {setError('Không thể tải trò chơi. Con thử lại nhé!')} finally {setLoading(false)}},[activity.activity_id,courseId,lessonId]); useEffect(()=>{void load()},[load]);
 const finish=useCallback(async(next:string[])=>{if(finishing)return;setFinishing(true);try{await coursesApi.completeMiniGameActivity(courseId,lessonId,activity.activity_id,next);onComplete()}catch{setError('Không thể lưu kết quả. Con thử lại nhé!')}finally{setFinishing(false)}},[activity.activity_id,courseId,finishing,lessonId,onComplete]);
 const choose=(card:MemoryMatchCard)=>{if(picked.length===2||matched.includes(card.pair_id)||picked.includes(card.card_id))return;const next=[...picked,card.card_id];setPicked(next);if(next.length===2){const chosen=cards.filter(x=>next.includes(x.card_id));if(chosen[0].pair_id===chosen[1].pair_id){const pairs=[...matched,chosen[0].pair_id];setMatched(pairs);setPicked([]);if(pairs.length===new Set(cards.map(x=>x.pair_id)).size)void finish(pairs)}else setTimeout(()=>setPicked([]),500)}};
 if(loading)return <ClayCard><ActivityIndicator color={BRAND.skyBlue}/></ClayCard>; if(error&&!cards.length)return <ClayCard><Text>{error}</Text><ClayButton color="blue" onPress={()=>void load()}>Thử lại</ClayButton></ClayCard>;
 return <View style={s.root}><Text style={s.title}>Ghép các thẻ giống nhau</Text><View style={s.grid}>{cards.map(c=>{const shown=picked.includes(c.card_id)||matched.includes(c.pair_id);const imageUrl=c.asset?.url??c.content;return <ClayCard key={c.card_id} onPress={()=>choose(c)} style={s.card}>{shown&&c.type==='image'&&imageUrl?<Image source={{uri:imageUrl}} style={s.image}/>:<Text style={s.cardText}>{shown?(c.content??'?'):'?'}</Text>}</ClayCard>})}</View>{error?<ClayButton color="blue" onPress={()=>void finish(matched)} loading={finishing}>Lưu lại</ClayButton>:null}</View>;
}; const s=StyleSheet.create({root:{gap:SPACING.md},title:{fontSize:FONT.sizes.lg,color:COLORS.textPrimary,fontWeight:'800',textAlign:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:SPACING.sm},card:{width:'47%',minHeight:96,justifyContent:'center',alignItems:'center'},cardText:{fontSize:FONT.sizes.lg,color:COLORS.textPrimary,textAlign:'center'},image:{width:72,height:72,resizeMode:'contain'}});
